// Metro requires static require() calls for asset bundling — no dynamic paths.
export const cardImages = {
    ace_clubs: require('../../../assets/cards/ace_clubs.png'),
    '2_clubs': require('../../../assets/cards/2_clubs.png'),
    '3_clubs': require('../../../assets/cards/3_clubs.png'),
    '4_clubs': require('../../../assets/cards/4_clubs.png'),
    '5_clubs': require('../../../assets/cards/5_clubs.png'),
    '6_clubs': require('../../../assets/cards/6_clubs.png'),
    '7_clubs': require('../../../assets/cards/7_clubs.png'),
    '8_clubs': require('../../../assets/cards/8_clubs.png'),
    '9_clubs': require('../../../assets/cards/9_clubs.png'),
    '10_clubs': require('../../../assets/cards/10_clubs.png'),
    jack_clubs: require('../../../assets/cards/jack_clubs.png'),
    queen_clubs: require('../../../assets/cards/queen_clubs.png'),
    king_clubs: require('../../../assets/cards/king_clubs.png'),

    ace_diamonds: require('../../../assets/cards/ace_diamonds.png'),
    '2_diamonds': require('../../../assets/cards/2_diamonds.png'),
    '3_diamonds': require('../../../assets/cards/3_diamonds.png'),
    '4_diamonds': require('../../../assets/cards/4_diamonds.png'),
    '5_diamonds': require('../../../assets/cards/5_diamonds.png'),
    '6_diamonds': require('../../../assets/cards/6_diamonds.png'),
    '7_diamonds': require('../../../assets/cards/7_diamonds.png'),
    '8_diamonds': require('../../../assets/cards/8_diamonds.png'),
    '9_diamonds': require('../../../assets/cards/9_diamonds.png'),
    '10_diamonds': require('../../../assets/cards/10_diamonds.png'),
    jack_diamonds: require('../../../assets/cards/jack_diamonds.png'),
    queen_diamonds: require('../../../assets/cards/queen_diamonds.png'),
    king_diamonds: require('../../../assets/cards/king_diamonds.png'),

    ace_hearts: require('../../../assets/cards/ace_hearts.png'),
    '2_hearts': require('../../../assets/cards/2_hearts.png'),
    '3_hearts': require('../../../assets/cards/3_hearts.png'),
    '4_hearts': require('../../../assets/cards/4_hearts.png'),
    '5_hearts': require('../../../assets/cards/5_hearts.png'),
    '6_hearts': require('../../../assets/cards/6_hearts.png'),
    '7_hearts': require('../../../assets/cards/7_hearts.png'),
    '8_hearts': require('../../../assets/cards/8_hearts.png'),
    '9_hearts': require('../../../assets/cards/9_hearts.png'),
    '10_hearts': require('../../../assets/cards/10_hearts.png'),
    jack_hearts: require('../../../assets/cards/jack_hearts.png'),
    queen_hearts: require('../../../assets/cards/queen_hearts.png'),
    king_hearts: require('../../../assets/cards/king_hearts.png'),

    ace_spades: require('../../../assets/cards/ace_spades.png'),
    '2_spades': require('../../../assets/cards/2_spades.png'),
    '3_spades': require('../../../assets/cards/3_spades.png'),
    '4_spades': require('../../../assets/cards/4_spades.png'),
    '5_spades': require('../../../assets/cards/5_spades.png'),
    '6_spades': require('../../../assets/cards/6_spades.png'),
    '7_spades': require('../../../assets/cards/7_spades.png'),
    '8_spades': require('../../../assets/cards/8_spades.png'),
    '9_spades': require('../../../assets/cards/9_spades.png'),
    '10_spades': require('../../../assets/cards/10_spades.png'),
    jack_spades: require('../../../assets/cards/jack_spades.png'),
    queen_spades: require('../../../assets/cards/queen_spades.png'),
    king_spades: require('../../../assets/cards/king_spades.png'),

    card_back: require('../../../assets/cards/card_back.png'),
} as const;
